# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppClusteringEMGlassoWeighted <- function(InputList, l, r, Pk_in, tol = 1e-3, max_iter = 250L) {
    .Call('_SelvarMix_rcppClusteringEMGlassoWeighted', PACKAGE = 'SelvarMix', InputList, l, r, Pk_in, tol, max_iter)
}

rcppDiscriminantAnalysisGlasso <- function(X_, labels_, nbClust, l, r) {
    .Call('_SelvarMix_rcppDiscriminantAnalysisGlasso', PACKAGE = 'SelvarMix', X_, labels_, nbClust, l, r)
}

LoglikelihoodObsGaussian <- function(YNA, mu, sigma, alpha, prop_pi) {
    .Call('_SelvarMix_LoglikelihoodObsGaussian', PACKAGE = 'SelvarMix', YNA, mu, sigma, alpha, prop_pi)
}

InitEMGaussian <- function(YNA, K, mecha, diag, init, samplesize) {
    .Call('_SelvarMix_InitEMGaussian', PACKAGE = 'SelvarMix', YNA, K, mecha, diag, init, samplesize)
}

MechanismEMGLM <- function(YNA, tik, mecha) {
    .Call('_SelvarMix_MechanismEMGLM', PACKAGE = 'SelvarMix', YNA, tik, mecha)
}

EMGaussian <- function(YNA, K, mecha, diag, rmax, init = NULL, tol = 0.0001, samplesize = NULL) {
    .Call('_SelvarMix_EMGaussian', PACKAGE = 'SelvarMix', YNA, K, mecha, diag, rmax, init, tol, samplesize)
}

LoglikelihoodObsGaussianMixed <- function(YNA, mu, sigma, alpha, beta, prop_pi, is_mnar, E_mu_list = NULL, E_sig_list = NULL) {
    .Call('_SelvarMix_LoglikelihoodObsGaussianMixed', PACKAGE = 'SelvarMix', YNA, mu, sigma, alpha, beta, prop_pi, is_mnar, E_mu_list, E_sig_list)
}

InitEMGaussianMixed <- function(YNA, K, mecha, is_mnar, diag, init, samplesize) {
    .Call('_SelvarMix_InitEMGaussianMixed', PACKAGE = 'SelvarMix', YNA, K, mecha, is_mnar, diag, init, samplesize)
}

MechanismEMGLMMixed <- function(YNA, tik, mecha, is_mnar, E_y_list, current_alpha, current_beta) {
    .Call('_SelvarMix_MechanismEMGLMMixed', PACKAGE = 'SelvarMix', YNA, tik, mecha, is_mnar, E_y_list, current_alpha, current_beta)
}

EMGaussianMixed <- function(YNA, K, mecha, is_mnar, diag, rmax, init = NULL, tol = 0.0001, samplesize = NULL) {
    .Call('_SelvarMix_EMGaussianMixed', PACKAGE = 'SelvarMix', YNA, K, mecha, is_mnar, diag, rmax, init, tol, samplesize)
}

rcppSelectS <- function(X, Order, nbCluster, framework, model_name, packSize, Crit, knownlabels, DA) {
    .Call('_SelvarMix_rcppSelectS', PACKAGE = 'SelvarMix', X, Order, nbCluster, framework, model_name, packSize, Crit, knownlabels, DA)
}

rcppSelectW <- function(X, Order, OtherVar, packSize) {
    .Call('_SelvarMix_rcppSelectW', PACKAGE = 'SelvarMix', X, Order, OtherVar, packSize)
}

rcppSelectR <- function(X, S, U, regmodel) {
    .Call('_SelvarMix_rcppSelectR', PACKAGE = 'SelvarMix', X, S, U, regmodel)
}

rcppCrit <- function(X, MyList, rgm, idm) {
    .Call('_SelvarMix_rcppCrit', PACKAGE = 'SelvarMix', X, MyList, rgm, idm)
}

