# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppClusteringEMGlassoWeighted <- function(InputList, l, r, Pk_in, tol = 1e-3, max_iter = 250L) {
    .Call(`_SelvarMixExt_rcppClusteringEMGlassoWeighted`, InputList, l, r, Pk_in, tol, max_iter)
}

rcppDiscriminantAnalysisGlasso <- function(X_, labels_, nbClust, l, r) {
    .Call(`_SelvarMixExt_rcppDiscriminantAnalysisGlasso`, X_, labels_, nbClust, l, r)
}

LoglikelihoodObsGaussian <- function(YNA, mu, sigma, alpha, prop_pi) {
    .Call(`_SelvarMixExt_LoglikelihoodObsGaussian`, YNA, mu, sigma, alpha, prop_pi)
}

InitEMGaussian <- function(YNA, K, mecha, diag, init, samplesize) {
    .Call(`_SelvarMixExt_InitEMGaussian`, YNA, K, mecha, diag, init, samplesize)
}

MechanismEMGLM <- function(YNA, tik, mecha) {
    .Call(`_SelvarMixExt_MechanismEMGLM`, YNA, tik, mecha)
}

EMGaussian <- function(YNA, K, mecha, diag, rmax, init = NULL, tol = 0.0001, samplesize = NULL) {
    .Call(`_SelvarMixExt_EMGaussian`, YNA, K, mecha, diag, rmax, init, tol, samplesize)
}

LoglikelihoodObsGaussianMixed <- function(YNA, mu, sigma, alpha, beta, prop_pi, is_mnar, E_mu_list = NULL, E_sig_list = NULL) {
    .Call(`_SelvarMixExt_LoglikelihoodObsGaussianMixed`, YNA, mu, sigma, alpha, beta, prop_pi, is_mnar, E_mu_list, E_sig_list)
}

InitEMGaussianMixed <- function(YNA, K, mecha, is_mnar, diag, init, samplesize) {
    .Call(`_SelvarMixExt_InitEMGaussianMixed`, YNA, K, mecha, is_mnar, diag, init, samplesize)
}

MechanismEMGLMMixed <- function(YNA, tik, mecha, is_mnar, E_y_list, current_alpha, current_beta) {
    .Call(`_SelvarMixExt_MechanismEMGLMMixed`, YNA, tik, mecha, is_mnar, E_y_list, current_alpha, current_beta)
}

EMGaussianMixed <- function(YNA, K, mecha, is_mnar, diag, rmax, init = NULL, tol = 0.0001, samplesize = NULL) {
    .Call(`_SelvarMixExt_EMGaussianMixed`, YNA, K, mecha, is_mnar, diag, rmax, init, tol, samplesize)
}

rcppSelectS <- function(X, Order, nbCluster, framework, model_name, packSize, Crit, knownlabels, DA) {
    .Call(`_SelvarMixExt_rcppSelectS`, X, Order, nbCluster, framework, model_name, packSize, Crit, knownlabels, DA)
}

rcppSelectW <- function(X, Order, OtherVar, packSize) {
    .Call(`_SelvarMixExt_rcppSelectW`, X, Order, OtherVar, packSize)
}

rcppSelectR <- function(X, S, U, regmodel) {
    .Call(`_SelvarMixExt_rcppSelectR`, X, S, U, regmodel)
}

rcppCrit <- function(X, MyList, rgm, idm) {
    .Call(`_SelvarMixExt_rcppCrit`, X, MyList, rgm, idm)
}

